app/booking/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, IntegerField #,DateField
from wtforms.validators import Required, Email, Length, Regexp, EqualTo, NumberRange
from wtforms import ValidationError
from wtforms.fields.html5 import DateField
from wtforms_components import DateRange
from datetime import datetime, date
from ..models import Customer, User, Airport
from dateutil.relativedelta import relativedelta
from .. import db

class BookingAgentCheckoutForm(FlaskForm):
    email = StringField('Customer Email', validators = [Required(),Email()])
    submit = SubmitField('Confirm Purchase')

    def validate_email(self, field):
        if not Customer.query.filter_by(email = field.data).first():
            raise ValidationError('Email does not belong to an existing customer')

class CustomerCheckoutForm(FlaskForm):
    submit = SubmitField('Confirm Purchase')

class TrackingSearchForm(FlaskForm):
    airport = SelectField('Airport:', validators = [Required()])
    date = DateField('Departure Date', validators = [Required(), DateRange(date.today())])
    submit = SubmitField('See Flights')

class SearchByFlightNum(FlaskForm):
    flight_num = StringField('Flight #')
    airline = SelectField('Select an Airline')
    submit = SubmitField('Check Flight')

class SearchMyFlights(FlaskForm):
    start_date = DateField('Begin:')
    end_date = DateField('End:')
    city = SelectField('City', default = (None, 'Optional'))
    submit = SubmitField('Search Flights')

    def validate_end_date(self, field):
        if field.data:
            if field.data < self.start_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_start_date(self, field):
        if field.data:
            if field.data > self.end_date.data:
                raise ValidationError('Please input a valid date range')

class SearchCustomerFlights(FlaskForm):
    start_date = DateField('Begin:')
    end_date = DateField('End:')
    city = SelectField('City', default = (None, 'Optional'))
    customer = SelectField('Customer', default = (None, 'All'))
    submit = SubmitField('Search Flights')

    def validate_end_date(self, field):
        if field.data:
            if field.data < self.start_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_start_date(self, field):
        if field.data:
            if field.data > self.end_date.data:
                raise ValidationError('Please input a valid date range')

class PersonalFinances(FlaskForm):
    start_date = DateField('Start Date:')
    end_date = DateField('End Date:')
    submit = SubmitField('Explore Finances')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.start_date.data:
            self.start_date.data = date.today() - relativedelta(years = 1)
        if not self.end_date.data:
            self.end_date.data = date.today()

    def validate_end_date(self, field):
        if field.data:
            if field.data < self.start_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_start_date(self, field):
        if field.data:
            if field.data > self.end_date.data:
                raise ValidationError('Please input a valid date range')

class CommissionForm(FlaskForm):
    start_date = DateField('Start Date:')
    end_date = DateField('End Date:')
    submit = SubmitField('Explore My Commission')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.start_date.data:
            self.start_date.data = date.today() - relativedelta(days = 30)
        if not self.end_date.data:
            self.end_date.data = date.today()

    def validate_end_date(self, field):
        if field.data:
            if field.data < self.start_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_start_date(self, field):
        if field.data:
            if field.data > self.end_date.data:
                raise ValidationError('Please input a valid date range')

class TopCustomerForm(FlaskForm):
    start_date = DateField('Start Date:', validators =[Required()])
    end_date = DateField('End Date:', validators =[Required()])
    top = IntegerField('Top N Customers:', validators =[Required()])
    submit = SubmitField('See Top Customers')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.top.data:
            self.top.data = 5

    def validate_end_date(self, field):
        if field.data:
            if field.data < self.start_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_start_date(self, field):
        if field.data:
            if field.data > self.end_date.data:
                raise ValidationError('Please input a valid date range')

app/booking/__init__.py
from flask import Blueprint

booking = Blueprint('booking',__name__)

from . import views
from ..models import Permission

@booking.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/booking/views.py
from flask import render_template, redirect, request, url_for, flash, session
from . import booking
from flask_login import login_user, login_required, logout_user, current_user
from ..models import Permission, Customer, User, Booking_agent, Airline_staff, Airport, Flight, Ticket, Airline, Airplane
from .forms import BookingAgentCheckoutForm, CustomerCheckoutForm, TrackingSearchForm, SearchByFlightNum, SearchMyFlights, PersonalFinances, SearchCustomerFlights, CommissionForm, TopCustomerForm
from ..main.forms import ExploreForm
# from .forms import
from datetime import datetime
from datetime import date
from dateutil.relativedelta import relativedelta
from ..decorators import permission_required
from collections import defaultdict
from .. import db
import re

@booking.route('/bookflight/<depart_id>', methods = ['GET','POST'])
def bookflight(depart_id):
    form = ExploreForm()
    form.departure_date.data = datetime.strptime(session['form']['departure_date'], '%a, %d %b %Y %H:%M:%S %Z')
    form.return_date.data = datetime.strptime(session['form']['return_date'], '%a, %d %b %Y %H:%M:%S %Z')
    form.departure_airport.data = session['form']['departure_airport']
    form.arrival_airport.data = session['form']['arrival_airport']
    airports = [(i,i) for (i,) in db.session.query(Airport.name).all()]
    form.departure_airport.choices = airports
    form.arrival_airport.choices = airports
    if request.method == "POST" and form.validate():
        start_date = form.departure_date.data
        ret_date = form.return_date.data
        dep_air = form.departure_airport.data
        arr_air = form.arrival_airport.data
        available_departure_flight = Flight.query.join(Ticket,(Ticket.flight_num == Flight.flight_num) & (Ticket.airline_name == Flight.airline_name), isouter = True) \
                    .join(Airplane, Flight.airplane_model == Airplane.id_num) \
                    .filter((Flight.departure == dep_air) & (Flight.arrival == arr_air) & (Flight.departure_date < start_date + relativedelta(days = 1)) & (Flight.departure_date >= date.today())) \
                    .group_by(Flight.flight_num, Flight.airline_name, Airplane.seat_capacity, Flight.departure_date, Flight.arrival_date, Flight.price) \
                    .having((db.func.max(Ticket.ticket_id) < Airplane.seat_capacity - 1) | (db.func.max(Ticket.ticket_id) == None)) \
                    .order_by(Flight.departure_date.desc()).all()
        session['ret_date'] = ret_date
        return render_template('booking/bookdeparture.html', dep_flights = available_departure_flight, permissions = Permission, form = form)
    air_name = request.args.get('airline')
    departure_flight = Flight.query.filter_by(flight_num = depart_id).filter_by(airline_name = air_name).first()
    dep_date = datetime.strptime(session.get('ret_date'), "%a, %d %b %Y %H:%M:%S %Z").replace(tzinfo=None)
    session['depart_flight_num'] = depart_id
    session['depart_flight_airline'] = air_name
    return_flights = Flight.query.join(Ticket,(Ticket.flight_num == Flight.flight_num) & (Ticket.airline_name == Flight.airline_name), isouter = True) \
                .join(Airplane, Flight.airplane_model == Airplane.id_num) \
                .filter((Flight.departure == departure_flight.arrival) & (Flight.arrival == departure_flight.departure) & (Flight.departure_date > dep_date - relativedelta(days = 1)) & (Flight.departure_date >= date.today())) \
                .group_by(Flight.flight_num, Flight.airline_name, Airplane.seat_capacity, Flight.departure_date, Flight.arrival_date, Flight.price) \
                .having((db.func.max(Ticket.ticket_id) < Airplane.seat_capacity - 1) | (db.func.max(Ticket.ticket_id) == None)) \
                .order_by(Flight.departure_date.asc()).all()
    # return_flights = Flight.query.filter_by(departure = departure_flight.arrival).filter_by(arrival = departure_flight.departure).filter(Flight.departure_date > dep_date - relativedelta(days=1)).order_by(Flight.departure_date.asc()).all()
    return render_template('booking/bookreturn.html', ret_flights = return_flights, permissions = Permission, form = form)

@booking.route('/checkout/<return_id>', methods = ['GET','POST'])
@login_required
def checkout(return_id):
    return_air_name = request.args.get('airline')
    departure_flight = Flight.query.filter_by(flight_num = session.get('depart_flight_num')).filter_by(airline_name = session.get('depart_flight_airline')).first()
    session['return_flight_num'] = return_id
    session['return_flight_airline'] = return_air_name
    depart_id = session.get('depart_flight_num')
    depart_air_name = session.get('depart_flight_airline')
    return_flight = Flight.query.filter_by(flight_num = return_id).filter_by(airline_name = return_air_name).first()
    booking_form = BookingAgentCheckoutForm()
    customer_form = CustomerCheckoutForm()
    total_price = "{0:.2f}".format(departure_flight.price + return_flight.price)
    if current_user.can(Permission.BOOK_FLIGHTS_AS_CUST):
        if customer_form.validate_on_submit():
            user_email = (Customer.query.filter_by(user_id = current_user.user_id).first()).email
            dep_ticket_id = Ticket.query.with_entities(Ticket.flight_num, Ticket.airline_name, db.func.max(Ticket.ticket_id)).filter((Ticket.flight_num == depart_id) & (Ticket.airline_name == depart_air_name)).group_by(Ticket.flight_num, Ticket.airline_name).first()
            ret_ticket_id = Ticket.query.with_entities(Ticket.flight_num, Ticket.airline_name, db.func.max(Ticket.ticket_id)).filter((Ticket.flight_num == return_id) & (Ticket.airline_name == return_air_name)).group_by(Ticket.flight_num, Ticket.airline_name).first()
            print(ret_ticket_id)
            if not dep_ticket_id:
                d_tick = 0
            else:
                d_tick = dep_ticket_id[2]
            if not ret_ticket_id:
                r_tick = 0
            else:
                r_tick = ret_ticket_id[2]
            dep_seats = Airplane.query.filter(Airplane.id_num == departure_flight.airplane_model).first()
            ret_seats = Airplane.query.filter(Airplane.id_num == return_flight.airplane_model).first()
            print(dep_ticket_id, ret_ticket_id, dep_seats.seat_capacity, ret_seats.seat_capacity)
            if d_tick < dep_seats.seat_capacity and r_tick < ret_seats.seat_capacity:
                dep_ticket = Ticket(ticket_id = d_tick + 1,
                                customer_email = user_email,
                                airline_name = session.get('depart_flight_airline'),
                                flight_num = session.get('depart_flight_num'),
                                booking_agent_ID = None,
                                date_purchased = datetime.now())

                ret_ticket = Ticket(ticket_id = r_tick + 1,
                                customer_email = user_email,
                                airline_name = session.get('return_flight_airline'),
                                flight_num = session.get('return_flight_num'),
                                booking_agent_ID = None,
                                date_purchased = datetime.now())
                db.session.add(dep_ticket)
                db.session.add(ret_ticket)
                db.session.commit()
                flash('Thanks for using Tripmetic for your Flight Services!')
                return redirect(url_for("main.index"))
            else:
                flash("We're sorry, but the flights you have requested are currently sold out!")
                return redirect(url_for("main.index"))
    elif current_user.can(Permission.BOOK_FLIGHTS_AS_AGENT):
        if booking_form.validate_on_submit():
            booking_id = (Booking_agent.query.filter_by(user_id = current_user.user_id).first()).booking_agent_id
            dep_ticket_id = Ticket.query.with_entities(Ticket.flight_num, Ticket.airline_name, db.func.max(Ticket.ticket_id)).filter((Ticket.flight_num == depart_id) & (Ticket.airline_name == depart_air_name)).group_by(Ticket.flight_num, Ticket.airline_name).first()
            ret_ticket_id = Ticket.query.with_entities(Ticket.flight_num, Ticket.airline_name, db.func.max(Ticket.ticket_id)).filter((Ticket.flight_num == return_id) & (Ticket.airline_name == return_air_name)).group_by(Ticket.flight_num, Ticket.airline_name).first()
            if not dep_ticket_id:
                d_tick = 0
            else:
                d_tick = dep_ticket_id[2]
            if not ret_ticket_id:
                r_tick = 0
            else:
                r_tick = ret_ticket_id[2]
            dep_seats = Airplane.query.filter(Airplane.id_num == departure_flight.airplane_model).first()
            ret_seats = Airplane.query.filter(Airplane.id_num == return_flight.airplane_model).first()
            if d_tick < dep_seats.seat_capacity and r_tick < ret_seats.seat_capacity:
                dep_ticket = Ticket(ticket_id = d_tick + 1,
                                customer_email = booking_form.email.data,
                                airline_name = session.get('depart_flight_airline'),
                                flight_num = session.get('depart_flight_num'),
                                booking_agent_ID = booking_id,
                                date_purchased = datetime.now())

                ret_ticket = Ticket(ticket_id = r_tick + 1,
                                customer_email = booking_form.email.data,
                                airline_name = session.get('return_flight_airline'),
                                flight_num = session.get('return_flight_num'),
                                booking_agent_ID = booking_id,
                                date_purchased = datetime.now())
                db.session.add(dep_ticket)
                db.session.add(ret_ticket)
                db.session.commit()
                flash('Thanks for using Tripmetic for your Flight Services!')
                return redirect(url_for("main.index"))

app/templates/booking/bookdeparture.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}

<div class = "container">
  <div class = "formwrapper">
    <h2>Book Your Departure Flight</h2>
    <form method = "POST" action = "{{url_for('main.bookdeparture')}}">
      <div class = "row">
        <div class = "col-md-5">
          <div class="form-field">{{ form.departure_airport.label }} {{ form.departure_airport }}
            {% if form.departure_airport.errors %}
              <ul class="errors">
          	{% for error in form.departure_airport.errors %}
          		<li>{{ error }}</li>
            {% endfor %}
              </ul>
            {% endif %}
          </div>
          <div class="form-field">{{ form.departure_date.label }} {{ form.departure_date }}
            {% if form.departure_date.errors %}
              <ul class="errors">
          	{% for error in form.departure_date.errors %}
          		<li>{{ error }}</li>
            {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>
        <div class = "col-md-5">
          <div class="form-field">{{ form.arrival_airport.label }} {{ form.arrival_airport }}
            {% if form.arrival_airport.errors %}
              <ul class="errors">
          	{% for error in form.arrival_airport.errors %}
          		<li>{{ error }}</li>
            {% endfor %}
              </ul>
            {% endif %}
          </div>
          <div class="form-field">{{ form.return_date.label }} {{ form.return_date }}
            {% if form.return_date.errors %}
              <ul class="errors">
          	{% for error in form.return_date.errors %}
          		<li>{{ error }}</li>
            {% endfor %}
              </ul>
            {% endif %}
          </div>
          {{ form.submit }}
          {{ form.hidden_tag() }}
        </div>
      </div>
      <div class = "row">
        <div class = "col-md-10">

        </div>
      </div>
    </form>
  </div>
  <div class = "row">
    <div class = "col-md-12">
      <table class = "table">
        <thead>
          <tr>
            <th scope="col">Airline</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Arrival Time</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody>
          {% for flight in dep_flights %}
            <tr class="clickable-row" data-href="{{ url_for('booking.bookflight', depart_id= flight.flight_num, airline=flight.airline_name)}}">
              <td>{{flight.airline_name}}</td>
              <td>{{flight.departure_date}}</td>
              <td>{{flight.arrival_date}}</td>
              <td>{{flight.price}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">

  jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
      window.location = $(this).data("href")
    })
  })

</script>
{% endblock %}

<!-- //this.selection (pull each attribute and send it)
//using jquery -->

app/templates/booking/bookreturn.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}
<div class = "container">
  <div class = "formwrapper">
    <h2>Book Your Return Flight</h2>
    <form method = "POST" action = "{{url_for('main.bookdeparture')}}">
      <div class = "row">
        <div class = "col-md-5">
          <div class="form-field">{{ form.departure_airport.label }} {{ form.departure_airport }}
            {% if form.departure_airport.errors %}
              <ul class="errors">
          	{% for error in form.departure_airport.errors %}
          		<li>{{ error }}</li>
            {% endfor %}
              </ul>
            {% endif %}
          </div>
          <div class="form-field">{{ form.departure_date.label }} {{ form.departure_date }}
            {% if form.departure_date.errors %}
              <ul class="errors">
          	{% for error in form.departure_date.errors %}
          		<li>{{ error }}</li>
            {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>
        <div class = "col-md-5">
          <div class="form-field">{{ form.arrival_airport.label }} {{ form.arrival_airport }}
            {% if form.arrival_airport.errors %}
              <ul class="errors">
          	{% for error in form.arrival_airport.errors %}
          		<li>{{ error }}</li>
            {% endfor %}
              </ul>
            {% endif %}
          </div>
          <div class="form-field">{{ form.return_date.label }} {{ form.return_date }}
            {% if form.return_date.errors %}
              <ul class="errors">
          	{% for error in form.return_date.errors %}
          		<li>{{ error }}</li>
            {% endfor %}
              </ul>
            {% endif %}
          </div>
          {{ form.submit }}
          {{ form.hidden_tag() }}
        </div>
      </div>
      <div class = "row">
        <div class = "col-md-10">

        </div>
      </div>
    </form>
  </div>
  <div class = "row">
    <div class = "col-md-12">
      <table class = "table">
        <thead>
          <tr>
            <th scope="col">Airline</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Arrival Time</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody>
          {% for flight in ret_flights %}
            <tr class="clickable-row" data-href="{{ url_for('booking.checkout', return_id= flight.flight_num, airline = flight.airline_name)}}">
              <td>{{flight.airline_name}}</td>
              <td>{{flight.departure_date}}</td>
              <td>{{flight.arrival_date}}</td>
              <td>{{flight.price}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">

  jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
      window.location = $(this).data("href")
    })
  })

</script>
</body>
{% endblock %}

<!-- //this.selection (pull each attribute and send it)
//using jquery -->

app/templates/booking/checkout.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}
<body>
  <table class = "table">
    <thead>
      <tr>
        <th scope="col">Airline</th>
        <th scope="col">Departure Time</th>
        <th scope="col">Arrival Time</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <th colspan = "3">Departure Flight Info: </th>
        </tr>
        <tr>
          <td>{{dep_flight.airline_name}}</td>
          <td>{{dep_flight.departure_date}}</td>
          <td>{{dep_flight.arrival_date}}</td>
        </tr>
        <tr>
          <th colspan = "3">Return Flight Info: </th>
        </tr>
        <tr>
          <td>{{ret_flight.airline_name}}</td>
          <td>{{ret_flight.departure_date}}</td>
          <td>{{ret_flight.arrival_date}}</td>
        </tr>
        <tr>
          <th colspan = "2">Total Cost:</th>
          <td>{{ tot_price }}</td>
        </tr>
    <tbody>
  </table>
  <div class="col-md-4">
    {% if current_user.can(permissions.BOOK_FLIGHTS_AS_CUST) %}
      {{ wtf.quick_form(cust_form) }}
    {% elif current_user.can(permissions.BOOK_FLIGHTS_AS_AGENT) %}
      {{ wtf.quick_form(book_form)}}
    {% endif %}
  </div>
</body>


{% endblock %}

app/templates/booking/commission.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
{% endblock %}
{% block page_content %}

<div class = "container">
  <div class = "row">
    <div class = "col-md-6">
      <h3>Track My Commission</h3>
      {{wtf.quick_form(form)}}
    </div>
  </div>
  <div class = "row">
    <div class = "col-md-8">
      <h3>Personal Stats in Date Range<h3>
      <h4>Total Commission: {{total_commission}}</h4>
      <h4>Average Commission: {{avg_commission}}</h4>
      <h4>Tickets Sold: {{total_tickets_sold}}</h4>
    </div>
  </div>
</div>
{% endblock %}

app/templates/booking/finances.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

  #chart {
    height: 40vh;
  }

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="http://d3js.org/d3.v4.min.js" charset="utf-8"></script>
<script src="https://momentjs.com/downloads/moment.js"></script>
{% endblock %}
{% block page_content %}

<div class = "container">
  <div class = "row">
    <div class = "col-md-6">
      <h3>Track My Spending</h3>
      {{wtf.quick_form(form)}}
    </div>
  </div>
  <div class = "row">
    <div class = "col-md-6">
      <br></br>
      <h4> Total Spend in Range: {{total_spend}}</h4>
    </div>
  </div>
  <div class = "row">
    <div class = "col-md-8" id = "chart">
      <h4> Monthly Spend in Range <h4>
    </div>
  </div>
</div>

<script>

  var padding = 50
  var data = []

  var options = {year: 'numeric', month: 'long'}

  {% for ticket in months %}
      var temp_data = {}
      temp_data["Month"] =  moment("{{ticket}}")
      temp_data['Total'] = parseFloat("{{months[ticket]}}")
      data.push(temp_data)
  {% endfor %}

  var width = document.getElementById("chart").clientWidth
  var height = document.getElementById("chart").clientHeight

  console.log(width, height)

  var month_totals = data.map(function(data){
    return data.Total
  })

// .toLocaleDateString(options)
  data.sort((a,b) => a.Month - b.Month)

  // .toLocaleDateString(options)

  data.forEach(function(d){
    d.Month = d.Month.format("MMM YYYY")
  })

  var max_value = Math.round(Math.max(...month_totals)/1000)*1000

  var xScale = d3.scaleBand()
                  .domain(data.map(function(d) {return d.Month}))
                  .padding(0.1)
                  .range([padding, width - padding])


  var yScale = d3.scaleLinear()
                  .domain([0, max_value])
                  .range([height - padding, padding])

  var svg = d3.select("#chart")
              .append("svg")
              .attr("width", width)
              .attr("height", height)
              .append("g")
              .attr("transform",
                  "translate(" + padding + "," +0 + ")");

  svg.selectAll('.bar')
      .data(data)
      .enter()
      .append("rect")
      .attr("class", "bar")
      .attr("x", function(d) {
        return xScale(d.Month)
      })
      .attr("width", xScale.bandwidth())
      .attr("y", function(d) {
        return yScale(d.Total)
      })
      .attr("height", function(d) {
        return (height - padding) - yScale(d.Total)
      })
      .style("fill", "rgb(100,100,300)")

  svg.append("g")
      .attr("transform", "translate(0," + (height - padding) + ")")
      .call(d3.axisBottom(xScale))

    svg.append("g")
        .call(d3.axisLeft(yScale))

  console.log(width)
//Next will be writing the scale

  console.log(data)

</script>
{% endblock %}

app/templates/booking/myflights.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}
<div class = "container">
  <div class = "row">
    <div class = "col-md-6">
      {% if current_user.can(permissions.BOOK_FLIGHTS_AS_CUST) %}
        <h3>Search My Flights</h3>
      {% elif current_user.can(permissions.BOOK_FLIGHTS_AS_AGENT) %}
        <h3>Search Customer Flights</h3>
      {% endif %}
      {{wtf.quick_form(form)}}
    </div>
  </div>
</div>
<div class = "container">
  <div class = "col-md-12">
    <div class = "row">
      <br></br>
      <table class = "table">
        <thead>
          <h4> Upcoming Flights </h4>
          <tr>
            <th scope="col">Airline</th>
            <th scope="col">Flight #</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Origin Airport</th>
            <th scope="col">Destination Airport</th>
            <th scope="col">Status</th>
            <th scope="col">Quantity</th>
          </tr>
        </thead>
        <tbody>
          {% for flights in upcoming %}
            <tr>
              <td>{{flights.airline_name}}</td>
              <td>{{flights.flight_num}}</td>
              <td>{{flights.departure_date}}</td>
              <td>{{flights.departure}}</td>
              <td>{{flights.arrival}}</td>
              <td>{{flights.status}}</td>
              <td>{{quantities[flights.flight_num][1]}}x</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
  </div>
  <div class = "col-md-12">
    <div class = "row">
      <table class = "table">
        <thead>
          <h4> Historical Flights </h4>
          <tr>
            <th scope="col">Airline</th>
            <th scope="col">Flight #</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Origin Airport</th>
            <th scope="col">Destination Airport</th>
            <th scope="col">Status</th>
            <th scope="col">Quantity</th>
          </tr>
        </thead>
        <tbody>
          {% for flights in historical %}
            <tr>
              <td>{{flights.airline_name}}</td>
              <td>{{flights.flight_num}}</td>
              <td>{{flights.departure_date}}</td>
              <td>{{flights.departure}}</td>
              <td>{{flights.arrival}}</td>
              <td>{{flights.status}}</td>
              <td>{{quantities[flights.flight_num][1]}}x</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}