app/agent/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, IntegerField, DecimalField
from wtforms.validators import Required, Email, Length, Regexp, EqualTo, NumberRange
from wtforms import ValidationError
from wtforms.fields.html5 import DateField, DateTimeField, TimeField
from wtforms_components import DateRange
from datetime import datetime, date
from ..models import Customer, User, Airport, Flight
from dateutil.relativedelta import relativedelta
from .. import db

class SearchAirlineFlights(FlaskForm):
    start_date = DateField('Begin:')
    end_date = DateField('End:')
    origin_city = SelectField('Origin City', default = (None, 'Optional'))
    destination_city = SelectField('Destination City', default = (None, 'Optional'))
    submit = SubmitField('Search Flights')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.start_date.data:
            self.start_date.data = date.today()
        if not self.end_date.data:
            self.end_date.data = date.today() + relativedelta(days = 30)

    def validate_end_date(self, field):
        if field.data:
            if field.data < self.start_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_start_date(self, field):
        if field.data:
            if field.data > self.end_date.data:
                raise ValidationError('Please input a valid date range')

class AddFlights(FlaskForm):
    origin_airport = SelectField('Origin Airport:', validators = [Required()])
    destination_airport = SelectField('Destination Airport:', validators = [Required()])
    airplane_id = SelectField('Airplane ID:', validators = [Required()])
    departure_date = DateField('Departure Date:', validators = [Required()])
    departure_time = TimeField('Departure Time: 12hr', validators = [Required()], format = "%H:%M")
    arrival_date = DateField('Arrival Date:', validators = [Required()])
    arrival_time = TimeField('Arrival Time: 12hr', validators = [Required()], format = "%H:%M")
    status = SelectField('Status:', validators = [Required()])
    price = DecimalField('Price', validators = [Required()])
    submit = SubmitField('Add Flight')

    def validate_price(self, field):
        if (field.data).as_tuple().exponent < -2:
            raise ValidationError('Please input a valid Price')

    def validate_departure_date(self, field):
        if field.data:
            if field.data > self.arrival_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_departure_time(self, field):
        if field.data:
            if self.departure_date.data == self.arrival_date.data:
                if field.data > self.arrival_time.data:
                    raise ValidationError('Arrival Time must be after Departure Time')

    def validate_origin_airport(self, field):
        if field.data:
            if field.data == self.destination_airport.data:
                raise ValidationError('Airports must differ!')

    def validate_arrival_date(self, field):
        if field.data:
            if field.data < self.departure_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_airplane_id(self, field):
        if field.data:
            taken = Flight.query.filter((Flight.airplane_id == field.data) & (Flight.departure_date >= self.departure_time.data) & (Flight.arrival_date < self.arrival_time.data)).all()
            if taken:
                raise ValidationError('The aircraft you requested is scheduled for the desired date range')

class UpdateStatus(FlaskForm):
    status = SelectField('Status:', validators = [Required()])
    submit = SubmitField('Update')

class AddAirplane(FlaskForm):
    model = SelectField('Select Aircraft:', validators = [Required()])
    submit = SubmitField('Add Airplane')

class AddAirport(FlaskForm):
    name = StringField('Airport Name', validators = [Required()])
    code = StringField('Airport Code', validators = [Required(), Length(min = 3), Length(max = 3)])
    city = StringField('City', validators = [Required()])
    country = StringField('Country', validators = [Required()])
    longitude = DecimalField('Longitude', validators = [Required()])
    latitude = DecimalField('Latitude', validators = [Required()])
    submit = SubmitField('Add Airport')

    def validate_code(self, field):
        if field.data:
            codes = list(zip(*Airport.query.with_entities(Airport.code).all()))[0]
            print(codes)
            if field.data in codes:
                raise ValidationError('This Airport Code Already Exists!')

    def validate_name(self, field):
        if field.data:
            names = list(zip(*Airport.query.with_entities(Airport.name).all()))[0]
            print(names)
            if field.data in names:
                raise ValidationError('An Airport with this Name Already Exists!')

class CustomerSearchForm(FlaskForm):
    start_date = DateField('Start Date', validators = [Required()])
    end_date = DateField('End Date', validators = [Required()])
    customers = SelectField('Select a Customer')
    submit = SubmitField('Search')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.start_date.data:
            self.start_date.data = date.today() - relativedelta(years = 1)
        if not self.end_date.data:
            self.end_date.data = date.today()

    def validate_end_date(self, field):
        if field.data:
            if field.data < self.start_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_start_date(self, field):
        if field.data:
            if field.data > self.end_date.data:
                raise ValidationError('Please input a valid date range')

class StatsForm(FlaskForm):
    start_date = DateField('Start Date', validators = [Required()])
    end_date = DateField('End Date', validators = [Required()])
    submit = SubmitField('View Stats')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.start_date.data:
            self.start_date.data = date.today() - relativedelta(months = 6)
        if not self.end_date.data:
            self.end_date.data = date.today()

    def validate_end_date(self, field):
        if field.data:
            if field.data < self.start_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_start_date(self, field):
        if field.data:
            if field.data > self.end_date.data:
                raise ValidationError('Please input a valid date range')


class TopDestForm(FlaskForm):
    start_date = DateField('Start Date', validators = [Required()])
    end_date = DateField('End Date', validators = [Required()])
    top_n = IntegerField('Number to Rank', validators = [Required()])
    submit = SubmitField('View Stats')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.start_date.data:
            self.start_date.data = date.today() - relativedelta(months = 6)
        if not self.end_date.data:
            self.end_date.data = date.today()
        if not self.top_n.data:
            self.top_n.data = 3

    def validate_end_date(self, field):
        if field.data:
            if field.data < self.start_date.data:
                raise ValidationError('Please input a valid date range')

    def validate_start_date(self, field):
        if field.data:
            if field.data > self.end_date.data:
                raise ValidationError('Please input a valid date range')

app/agent/__init__.py
from flask import Blueprint

agent = Blueprint('agent',__name__)

from . import views
from ..models import Permission

@agent.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/agent/views.py
from flask import render_template, redirect, request, url_for, flash, session
from . import agent
from flask_login import login_user, login_required, logout_user, current_user
from ..models import Permission, Customer, User, Booking_agent, Airline_staff, Airport, Flight, Ticket, Airline, Airplane, Airline_stock, Status
from .forms import SearchAirlineFlights, AddFlights, UpdateStatus, AddAirplane, AddAirport, CustomerSearchForm, StatsForm, TopDestForm
from datetime import datetime
from datetime import date
from dateutil.relativedelta import relativedelta
from ..decorators import permission_required
from collections import defaultdict
from .. import db
import re

@agent.route('/airlineflights', methods = ['GET', 'POST'])
@login_required
@permission_required(Permission.MANAGE_AIRLINES)
def airlineflights():
    #on-click functionality: Show all customers of a particular flight
    line = (Airline_staff.query.filter(Airline_staff.user_id == current_user.user_id).first()).airline
    print(line)
    default_start = date.today()
    default_end = date.today() + relativedelta(days = 31)
    upcoming = Flight.query.filter((Flight.departure_date > default_start) & (Flight.departure_date < default_end) & (Flight.airline_name == line)).order_by(Flight.departure_date.asc()).all()
    form = SearchAirlineFlights()
    cities = Airport.query.with_entities(Airport.city).order_by(Airport.city.asc())
    form.origin_city.choices = [('None', 'Optional')] + [(i.city, i.city) for i in cities]
    form.destination_city.choices = [('None', 'Optional')] + [(i.city, i.city) for i in cities]
    if form.validate_on_submit():
        if form.origin_city.data != "None" and form.destination_city.data != "None":
            origin_airports = Airport.query.filter_by(city = form.origin_city.data).all()
            destination_airports = Airport.query.filter_by(city = form.destination_city.data).all()
            default_start = form.start_date.data
            default_end = form.end_date.data
            upcoming = Flight.query.filter((Flight.airline_name == line) & ((Flight.arrival.in_([i.name for i in destination_airports])) & (Flight.departure.in_([i.name for i in origin_airports]))) & (Flight.departure_date > default_start) & (Flight.departure_date < default_end)).order_by(Flight.departure_date.asc()).all()
            return render_template('agent/airlineflights.html', permissions = Permission, form = form, upcoming = upcoming, line = line)
        elif form.origin_city.data != "None":
            origin_airports = Airport.query.filter_by(city = form.origin_city.data).all()
            default_start = form.start_date.data
            default_end = form.end_date.data
            upcoming = Flight.query.filter((Flight.airline_name == line) & (Flight.departure.in_([i.name for i in origin_airports])) & (Flight.departure_date > default_start) & (Flight.departure_date < default_end)).order_by(Flight.departure_date.asc()).all()
            return render_template('agent/airlineflights.html', permissions = Permission, form = form, upcoming = upcoming, line = line)
        elif form.destination_city.data != "None":
            destination_airports = Airport.query.filter_by(city = form.destination_city.data).all()
            default_start = form.start_date.data
            default_end = form.end_date.data
            upcoming = Flight.query.filter((Flight.airline_name == line) & (Flight.arrival.in_([i.name for i in destination_airports])) & (Flight.departure_date > default_start) & (Flight.departure_date < default_end)).order_by(Flight.departure_date.asc()).all()
            return render_template('agent/airlineflights.html', permissions = Permission, form = form, upcoming = upcoming, line = line)
        else:
            default_start = form.start_date.data
            default_end = form.end_date.data
            upcoming = Flight.query.filter((Flight.departure_date > default_start) & (Flight.departure_date < default_end) & (Flight.airline_name == line)).order_by(Flight.departure_date.asc()).all()
            return render_template('agent/airlineflights.html', permissions = Permission, form = form, upcoming = upcoming, line = line)
    return render_template('agent/airlineflights.html', permissions = Permission, form = form, upcoming = upcoming, line = line)

@agent.route('/flightpassengers/<flight_num>', methods = ['GET', 'POST'])
@login_required
@permission_required(Permission.MANAGE_AIRLINES)
def flightpassengers(flight_num):
    line = (Airline_staff.query.filter(Airline_staff.user_id == current_user.user_id).first()).airline
    passengers = Ticket.query.join(Customer, (Customer.email == Ticket.customer_email)).filter((Ticket.flight_num == flight_num) & (Ticket.airline_name == line)).all()
    if request.method == "POST" and request.form['name'] == "return":
        return url_for('agent.airlineflights')
    return render_template('agent/flightpassengers.html', permissions = Permission, passengers = passengers, flight_number = flight_num, line = line)

@agent.route('/addflights', methods = ['GET','POST'])
@login_required
@permission_required(Permission.MANAGE_AIRLINES)
def addflights():
    line = (Airline_staff.query.filter(Airline_staff.user_id == current_user.user_id).first()).airline
    default_start = date.today()
    default_end = date.today() + relativedelta(days = 31)
    upcoming = Flight.query.filter((Flight.departure_date > default_start) & (Flight.departure_date < default_end) & (Flight.airline_name == line)).order_by(Flight.departure_date.asc()).all()
    form = AddFlights()
    airports = [(i,i) for (i,) in db.session.query(Airport.name).all()]
    airplane_ids = Airline_stock.query.filter((Airline_stock.airline_name == line)).with_entities(Airline_stock.unique_id).distinct().all()
    status_opt = Status.query.all()
    form.origin_airport.choices = airports
    form.destination_airport.choices = airports
    form.airplane_id.choices = [(i,i) for (i,) in airplane_ids]
    form.status.choices = [(i.status, i.status) for i in status_opt]
    if form.validate_on_submit():
        airplane_id = form.airplane_id.data
        airplane_model = Airline_stock.query.filter(Airline_stock.unique_id == airplane_id).with_entities(Airline_stock.model).first()[0]
        flight_count = Flight.query.filter((Flight.airline_name == line) & (Flight.airplane_id == airplane_id)).with_entities(db.func.count(Flight.flight_num)).first()[0]
        departure_date = datetime.combine(form.departure_date.data,form.departure_time.data)
        arrival_date = datetime.combine(form.arrival_date.data,form.arrival_time.data)
        flight_num = flight_count + 1
        new_flight = Flight(flight_num = '{}{:06d}'.format(airplane_id,flight_num),
                            price = form.price.data,
                            airline_name = line,
                            arrival = form.origin_airport.data,
                            departure = form.destination_airport.data,
                            arrival_date = arrival_date,
                            departure_date = departure_date,
                            airplane_id = airplane_id,
                            airplane_model = airplane_model,
                            status = form.status.data
                            )
        db.session.add(new_flight)
        db.session.commit()
        flash('The Flight has been added.')
        return redirect(url_for('main.index'))
    return render_template('agent/addflights.html', permissions = Permission, upcoming = upcoming, form = form)

@agent.route('/updatestatus/<flight_id>', methods = ['GET','POST'])
@login_required
@permission_required(Permission.MANAGE_AIRLINES)
def updatestatus(flight_id):
    line = (Airline_staff.query.filter(Airline_staff.user_id == current_user.user_id).first()).airline
    flight = Flight.query.filter((Flight.flight_num == flight_id) & (Flight.airline_name == line)).first()
    form = UpdateStatus()
    status_opt = Status.query.all()
    form.status.choices = [(i.status, i.status) for i in status_opt]
    if form.validate_on_submit():
        flight.status = form.status.data
        db.session.commit()
        flash('The Flight Status has been updated.')
        return redirect(url_for('main.index'))
    return render_template('agent/updatestatus.html', permissions = Permission, flight = flight, form = form)

@agent.route('/addplanes', methods = ['GET','POST'])
@login_required
@permission_required(Permission.MANAGE_AIRLINES)
def addplanes():
    line = (Airline_staff.query.filter(Airline_staff.user_id == current_user.user_id).first()).airline
    planes = Airline_stock.query.join(Airplane, (Airline_stock.model == Airplane.id_num)).filter(Airline_stock.airline_name == line).all()
    print(planes)
    form = AddAirplane()
    #can use airplane models instead of id because of unique constraint
    form.model.choices = [(None, 'Select Flight')] + [(i.id_num, i.aircraft_name) for i in Airplane.query.order_by(Airplane.aircraft_name.asc()).all()]
    if form.validate_on_submit():
        if form.model.data:
            id_number = form.model.data
            plane = Airline_stock.query.filter((Airline_stock.airline_name == line) & (Airline_stock.model == id_number)).with_entities(Airline_stock.model, db.func.count(Airline_stock.unique_id)).first()
            if plane[0]:
                new_plane = Airline_stock(model = plane[0],
                                        unique_id = '{}_{:04d}'.format(plane[0],plane[1] + 1),
                                        airline_name = line)
            else:
                new_plane = Airline_stock(model = id_number,
                                            unique_id = '{}_{:04d}'.format(id_number,1),
                                            airline_name = line)
            db.session.add(new_plane)
            db.session.commit()

app/templates/agent/addairport.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - add airports{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}
<div class = "container">
  <div class = "row">
    <div class = "col-md-6">
      <h3>Add Airports</h3>
      {{wtf.quick_form(form)}}
      {{ form.hidden_tag() }}
    </div>
  </div>
</div>

{% endblock %}

app/templates/agent/addflights.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}
<div class = "container">
  <div class = "row">
    <div class = "col-md-6">
      <h3>Add {{line}} Flights</h3>
      {{wtf.quick_form(form)}}
      {{ form.hidden_tag() }}
    </div>
  </div>
</div>
<div class = "container">
  <div class = "col-md-12">
    <div class = "row">
      <br></br>
      <table class = "table">
        <thead>
          <h4> Upcoming Flights </h4>
          <tr>
            <th scope="col">Flight #</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Origin Airport</th>
            <th scope="col">Destination Airport</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          {% for flights in upcoming %}
            <tr>
              <td>{{flights.flight_num}}</td>
              <td>{{flights.departure_date}}</td>
              <td>{{flights.departure}}</td>
              <td>{{flights.arrival}}</td>
              <td>{{flights.status}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

app/templates/agent/addplanes.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}
<div class = "container">
  <div class = "col-md-12">
    <div class = "row">
      <br></br>
      <table class = "table">
        <thead>
          <h4> Current {{line}} Airplane Stock </h4>
          <tr>
            <th scope="col">Model</th>
            <th scope="col">Aircraft</th>
            <th scope="col">Unique Identifier</th>
          </tr>
        </thead>
        <tbody>
          {% for plane in planes %}
            <tr>
              <td>{{plane.model}}</td>
              <td>{{plane.airplane.aircraft_name}}</td>
              <td>{{plane.unique_id}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
  </div>
</div>
<div class = "container">
  <div class = "row">
    <div class = "col-md-6">
      <h3>Add {{line}} Airplane Stock</h3>
      {{wtf.quick_form(form)}}
      {{ form.hidden_tag() }}
    </div>
  </div>
</div>
{% endblock %}

app/templates/agent/airlineflights.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}
<div class = "container">
  <div class = "row">
    <div class = "col-md-6">
      <h3>Search Flights: {{line}}</h3>
      {{wtf.quick_form(form)}}
      {{ form.hidden_tag() }}
    </div>
  </div>
</div>
<div class = "container">
  <div class = "col-md-12">
    <div class = "row">
      <br></br>
      <table class = "table">
        <thead>
          <h4> Upcoming Flights </h4>
          <tr>
            <th scope="col">Airline</th>
            <th scope="col">Flight #</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Origin Airport</th>
            <th scope="col">Destination Airport</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          {% for flights in upcoming %}
            <tr class="clickable-row" data-href="{{ url_for('agent.flightpassengers', flight_num = flights.flight_num)}}">
              <td>{{flights.airline_name}}</td>
              <td>{{flights.flight_num}}</td>
              <td>{{flights.departure_date}}</td>
              <td>{{flights.departure}}</td>
              <td>{{flights.arrival}}</td>
              <td>{{flights.status}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
  </div>
</div>

<script type="text/javascript">

    jQuery(document).ready(function($) {
      $(".clickable-row").click(function() {
        window.location = $(this).data("href")
      })
    })

</script>

{% endblock %}

app/templates/agent/bookingagents.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - booking agent{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}

<div class = "container">
  <div class = "col-md-6">
    <table class = "table">
      <thead>
        <h4> Top 5 by Tickets Sold (Past Month)</h4>
        <tr>
          <th scope="col">Rank</th>
          <th scope="col">Booking Agent Email</th>
          <th scope="col">Booking Agent ID</th>
          <th scope="col">Tickets Sold</th>
        </tr>
      </thead>
      <tbody>
        {% for i in top_tickets_month %}
          <tr>
            <td>{{loop.index0 + 1}}</td>
            <td>{{top_tickets_month[loop.index0][0]}}</td>
            <td>{{top_tickets_month[loop.index0][1]}}</td>
            <td>{{top_tickets_month[loop.index0][2]}}</td>
          </tr>
        {% endfor %}
      <tbody>
    </table>
    <table class = "table">
      <thead>
        <h4> Top 5 by Commission Earned (Past Month)</h4>
        <tr>
          <th scope="col">Rank</th>
          <th scope="col">Booking Agent Email</th>
          <th scope="col">Booking Agent ID</th>
          <th scope="col">Commission Earned</th>
        </tr>
      </thead>
      <tbody>
        {% for i in top_commission_month %}
          <tr>
            <td>{{loop.index0 + 1}}</td>
            <td>{{top_commission_month[loop.index0][0]}}</td>
            <td>{{top_commission_month[loop.index0][1]}}</td>
            <td>{{"${0:.2f}".format(top_commission_month[loop.index0][2])}}</td>
          </tr>
        {% endfor %}
      <tbody>
    </table>
  </div>
  <div class = "col-md-6">
    <table class = "table">
      <thead>
        <h4> Top 5 by Tickets Sold (Past Year)</h4>
        <tr>
          <th scope="col">Rank</th>
          <th scope="col">Booking Agent Email</th>
          <th scope="col">Booking Agent ID</th>
          <th scope="col">Tickets Sold</th>
        </tr>
      </thead>
      <tbody>
        {% for i in top_tickets_year %}
          <tr>
            <td>{{loop.index0 + 1}}</td>
            <td>{{top_tickets_year[loop.index0][0]}}</td>
            <td>{{top_tickets_year[loop.index0][1]}}</td>
            <td>{{top_tickets_year[loop.index0][2]}}</td>
          </tr>
        {% endfor %}
      <tbody>
    </table>
    <table class = "table">
      <thead>
        <h4> Top 5 by Commission Earned (Past Year)</h4>
        <tr>
          <th scope="col">Rank</th>
          <th scope="col">Booking Agent Email</th>
          <th scope="col">Booking Agent ID</th>
          <th scope="col">Commission Earned</th>
        </tr>
      </thead>
      <tbody>
        {% for i in top_commission_month %}
          <tr>
            <td>{{loop.index0 + 1}}</td>
            <td>{{top_commission_year[loop.index0][0]}}</td>
            <td>{{top_commission_year[loop.index0][1]}}</td>
            <td>{{"${0:.2f}".format(top_commission_year[loop.index0][2])}}</td>
          </tr>
        {% endfor %}
      <tbody>
    </table>
  </div>
</div>

{% endblock %}

app/templates/agent/customerflightinfo.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Book</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}
<div class = "container">
  <div class = "row">
    <div class = "col-md-10">
      <h3>Flights for {{customer.last_name}}, {{customer.first_name}}</h3>
    </div>
    <div class = "col-md-2 return">
      <form method = "GET" name = "return" action = "{{url_for('agent.customers')}}">
        <input type = "submit" name = "return_button" value = "return"></input>
      </form>
    </div>
  </div>
  <div class = "row">
    <div class = "col-md-12">
      <table class = "table">
        <thead>
          <tr>
            <th scope="col">Airline</th>
            <th scope="col">Flight #</th>
            <th scope="col">Departure Time</th>
            <th scope="col">Origin</th>
            <th scope="col">Destination</th>
          </tr>
        </thead>
        <tbody>
          {% for flight in flights %}
            <tr>
              <td>{{flight.airline_name}}</td>
              <td>{{flight.flight_num}}</td>
              <td>{{flight.flight.departure_date}}</td>
              <td>{{flight.flight.departure}}</td>
              <td>{{flight.flight.arrival}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
  </div>


{% endblock %}

app/templates/agent/updatestatus.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}tripmetic - departure{% endblock %}
{% block head %}
{{ super() }}
<meta charset='utf-8'>
<title>Update</title>
<style type="text/css">

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block page_content %}
<div class = "container">
  <div class = "col-md-12">
    <table class = "table">
      <thead>
        <h4> Flight to Update: </h4>
        <tr>
          <th scope="col">Airline</th>
          <th scope="col">Flight #</th>
          <th scope="col">Departure Time</th>
          <th scope="col">Destination</th>
          <th scope="col">Status</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <form method = "POST" action = "{{url_for('agent.updatestatus', flight_id=flight.flight_num)}}">
          <tr>
            <td>{{flight.airline_name}}</td>
            <td>{{flight.flight_num}}</td>
            <td>{{(flight.departure_date).strftime('%H:%M') }}</td>
            <td>{{flight.arrival}}</td>
            <td>
              <div class="form-field"> {{ form.status }}
                {% if form.status.errors %}
                  <ul class="errors">
              	{% for error in form.status.errors %}
              		<li>{{ error }}</li>
                {% endfor %}
                  </ul>
                {% endif %}
              </div>
            </td>
            <td>
              {{ form.submit }}
              {{ form.hidden_tag() }}
            </td>
          </tr>
        </form>
      <tbody>
    </table>
  </div>
</div>

{% endblock %}